// keywords.js
export const keywords = [
  "soutien informatique Saguenay",
  "aide informatique Saguenay",
  "formation informatique Saguenay prix abordables",
  "assistance informatique Saguenay",
  "dépannage informatique Saguenay tarifs abordables",
  "autonomie numérique Saguenay",
  "ateliers informatique Saguenay prix compétitifs",
  "soutien ordinateur Saguenay",
  "aide en ligne Saguenay abordable",
  "développement web Saguenay prix raisonnables",
  "sécurité informatique Saguenay",
  "transition numérique Saguenay",
  "cours informatique Saguenay pas cher",
  "accompagnement informatique personnalisé Saguenay",
  "Kimberly Rousse informatique Saguenay",
  "soutien informatique Chicoutimi prix abordables",
  "aide informatique Chicoutimi",
  "formation informatique Chicoutimi",
  "assistance informatique Chicoutimi tarifs abordables",
  "dépannage informatique Chicoutimi",
  "autonomie numérique Chicoutimi prix compétitifs",
  "ateliers informatique Chicoutimi",
  "soutien ordinateur Chicoutimi abordable",
  "aide en ligne Chicoutimi",
  "développement web Chicoutimi prix raisonnables",
  "sécurité informatique Chicoutimi",
  "transition numérique Chicoutimi pas cher",
  "cours informatique Chicoutimi",
  "accompagnement informatique personnalisé Chicoutimi",
  "Kimberly Rousse informatique Chicoutimi",
  "soutien informatique Jonquière prix abordables",
  "aide informatique Jonquière",
  "formation informatique Jonquière tarifs abordables",
  "assistance informatique Jonquière",
  "dépannage informatique Jonquière prix compétitifs",
  "autonomie numérique Jonquière",
  "ateliers informatique Jonquière abordable",
  "soutien ordinateur Jonquière",
  "aide en ligne Jonquière prix raisonnables",
  "développement web Jonquière",
  "sécurité informatique Jonquière pas cher",
  "transition numérique Jonquière",
  "cours informatique Jonquière",
  "accompagnement informatique personnalisé Jonquière",
  "Kimberly Rousse informatique Jonquière",
  "soutien informatique La Baie prix abordables",
  "aide informatique La Baie",
  "formation informatique La Baie tarifs abordables",
  "assistance informatique La Baie",
  "dépannage informatique La Baie prix compétitifs",
  "autonomie numérique La Baie",
  "ateliers informatique La Baie abordable",
  "soutien ordinateur La Baie",
  "aide en ligne La Baie prix raisonnables",
  "développement web La Baie",
  "sécurité informatique La Baie pas cher",
  "transition numérique La Baie",
  "cours informatique La Baie",
  "accompagnement informatique personnalisé La Baie",
  "Kimberly Rousse informatique La Baie",
  "prix abordables soutien informatique Saguenay",
  "tarifs abordables aide informatique Saguenay",
  "prix compétitifs formation informatique Saguenay",
  "abordable assistance informatique Saguenay",
  "prix raisonnables dépannage informatique Saguenay",
  "pas cher autonomie numérique Saguenay",
  "cours bureautique Saguenay pas cher",
].join(', ');